import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Footer, Nav } from './components'
import { GeneralAppContext } from './context/AppContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SayFamilyFoundation',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="light" lang="en">
      <body className={`box-content relative dark:bg-[#191A26] dark:text-gray-300`}>
        <GeneralAppContext>
          <Nav/>
           {children}
          <Footer/>
        </GeneralAppContext>
    </body>
    </html>
  )
}
