import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Footer, Nav } from './components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SayFoundation',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div data-theme="light" lang="en">
      <Nav/>
      <body className={inter.className}>{children}</body>
      <Footer/>
    </div>
  )
}
